import React, { useEffect, useState } from "react";
import Head from "next/head";
import { Button } from "@chakra-ui/react";
import styles from "../../styles/Home.module.css";
import Link from "next/link";
import Navbar from "../../containers/NavBar/Navbar";

import { useRouter } from "next/router";

import Club from "../../components/Club/Club";

import clubdata from "../../data/clubs.json";

import { useStoreState } from "easy-peasy";
import { createUser } from "../../APIs/api.actions";
import { getClubs } from "../../APIs/api.actions";

export default function Home() {
  const router = useRouter();
  const userid = useStoreState((state) => state.user.userid);
  const user = useStoreState((state) => state.user);

  const [bookClubs, setBookClubs] = useState([]);

  useEffect(() => {
    console.log("in");
    if (userid) {
      router.push("/Dashboard/Dashboard");
    }
  }, []);

  useEffect(() => {
    getClubs()
      .then((res) => {
        setBookClubs(res.data);
      })
      .catch((err) => {
        console.log(err);
      });
  }, []);

  return (
    <div>
      <Navbar username={user.displayName} user={user}/>
      <Head>
        <title>booktubes.club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to booktubes.club</h1>

        <p className={styles.description}>
          <Button mr={4} colorScheme="blue">
            <Link href="/auth/Login">
              <a> Sign In</a>
            </Link>
          </Button>
          <Button variant={"outline"} mr={4} colorScheme="blue">
            <Link href="/auth/Login">
              <a> Sign Up</a>
            </Link>
          </Button>
        </p>

        <div className={styles.myclub_wrapper}>
          <div className={styles.myclub}>
            {/* {clubdata.data.slice(0, 4).map((club) => {
              return <Club type="all" club={club} />;
            })} */}
            {bookClubs.map((club) => {
              return <Club type="all" club={club} />;
            })}
          </div>
        </div>
      </main>
      <footer className={styles.footer}>
        Powered by <span className={styles.logo}>booktubes.club</span>
      </footer>
    </div>
  );
}
