import React, { useEffect } from "react";
import Head from "next/head";
import { Button } from "@chakra-ui/react";
import styles from "../../styles/Home.module.css";
import Link from "next/link";
import { useRouter } from "next/router";

import Club from "../../components/Club/Club";

import clubdata from "../../data/clubs.json";

import { useStoreState } from "easy-peasy";

export default function Home() {
  const router = useRouter();
  const userid = useStoreState((state) => state.user.userid);

  useEffect(() => {
    if (userid) {
      router.push("/dashboard");
    }
  }, []);

  return (
    <div>
      <Head>
        <title>booktubes.club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to booktubes.club</h1>

        <p className={styles.description}>
          <Button mr={4} colorScheme="blue">
            <Link href="/auth/Login">
              <a> Sign In</a>
            </Link>
          </Button>
          <Button variant={"outline"} mr={4} colorScheme="blue">
            <Link href="/auth/Login">
              <a> Sign Up</a>
            </Link>
          </Button>
        </p>

        <div className={styles.myclub}>
          {clubdata.data.slice(0, 4).map((club) => {
            return <Club type="all" club={club} />;
          })}
        </div>
      </main>
      <footer className={styles.footer}>
        Powered by <span className={styles.logo}>booktubes.club</span>
      </footer>
    </div>
  );
}
